#scope_module

__macro_generated_selectors_t :: struct #type_info_no_size_complaint {
    // stuff in Metal.jai
    newMTL4CommandQueue: *void = ---;
    newCommandBuffer: *void = ---;
    newCommandAllocator: *void = ---;
    present: *void = ---;

    //MTL4CommandQueue
    commit_count_: *void = ---;
    signalDrawable_: *void = ---;
    waitForDrawable_: *void = ---;

    //MTL4CommandBuffer
    renderCommandEncoderWithDescriptor_ : *void = ---;
    renderCommandEncoderWithDescriptor_options_ : *void = ---;
    beginCommandBufferWithAllocator_ : *void = ---;

    //MTL4CommandAllocator
    reset : *void = ---;

    //MTL4RenderCommandEncoder
    endEncoding : *void = ---;
    setRenderPipelineState_ : *void = ---;
    setCullMode_ : *void = ---;
    colorAttachments : *void = ---;

    Placeholder : *void = ---;
}
__macro_generated_selectors : __macro_generated_selectors_t;


